"use client";

import { useCallback, useEffect, useState } from "react";
import { AdminConfirmDialog, AdminEmptyState, AdminErrorState, AdminLoadingState, AdminPageHeader, AdminStatus, OperationalCardList, OperationalTable, TechnicalDetails } from "@/components/admin";
import { useAdminCandidate } from "@/lib/admin/AdminContext";

type CompanyRow = { id:number; name:string; sourceType:string; isActive:number; connectorHealth:string; resolutionStatus:string; lastScannedAt:string|null; lastScanStatus:string|null; consecutiveFailures:number; lastErrorMessage:string|null; activeJobs:number; careerPageUrl:string|null; discoveryReason:string|null };
type ResponseData = { companies:CompanyRow[]; page:number; total:number; totalPages:number };

export default function AdminCompaniesPage() {
  const { candidateId } = useAdminCandidate();
  const [search,setSearch]=useState(""); const [active,setActive]=useState(""); const [health,setHealth]=useState(""); const [sort,setSort]=useState("name"); const [page,setPage]=useState(1);
  const [data,setData]=useState<ResponseData|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<number|null>(null); const [confirm,setConfirm]=useState<{company:CompanyRow; action:"delete"|"toggle"}|null>(null);
  const load=useCallback(async()=>{ try { const params=new URLSearchParams({candidateId:String(candidateId),page:String(page),limit:"25",search,active,health,sort}); const res=await fetch(`/api/admin/companies?${params}`); if(!res.ok) throw new Error((await res.json()).error??"Companies unavailable"); setData(await res.json()); setError(null);} catch(e){setError(e instanceof Error?e.message:"Companies unavailable");}},[candidateId,page,search,active,health,sort]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),150);return()=>clearTimeout(timer)},[load]);
  async function scan(company:CompanyRow){setBusy(company.id);try{const res=await fetch(`/api/scan?candidateId=${candidateId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyId:company.id})});if(!res.ok)throw new Error((await res.json()).message??"Scan failed");await load();}catch(e){setError(e instanceof Error?e.message:"Scan failed")}finally{setBusy(null)}}
  async function confirmAction(){if(!confirm)return;setBusy(confirm.company.id);try{const url=`/api/companies/${confirm.company.id}?candidateId=${candidateId}`;const res=await fetch(url,confirm.action==="delete"?{method:"DELETE"}:{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_active:!confirm.company.isActive})});if(!res.ok)throw new Error((await res.json()).error??"Action failed");setConfirm(null);await load();}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(null)}}
  if(error&&!data)return <AdminErrorState detail={error} retry={()=>void load()}/>; if(!data)return <AdminLoadingState label="Loading company registry"/>;
  return <div className="admin-page-stack"><AdminPageHeader eyebrow="Registry" title="Companies" description="Search, filter, and operate the company source registry without loading the entire corpus into the browser." />
    {error&&<div className="admin-inline-error" role="alert">{error}</div>}
    <div className="admin-filter-bar"><label><span>Search</span><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Company name"/></label><label><span>Active state</span><select value={active} onChange={e=>{setActive(e.target.value);setPage(1)}}><option value="">All</option><option value="active">Active</option><option value="paused">Paused</option></select></label><label><span>Health</span><select value={health} onChange={e=>{setHealth(e.target.value);setPage(1)}}><option value="">All</option><option value="healthy">Healthy</option><option value="degraded">Degraded</option><option value="down">Down</option><option value="unknown">Unknown</option></select></label><label><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Company</option><option value="last_scan">Last scan</option><option value="failures">Failures</option></select></label></div>
    {data.companies.length===0?<AdminEmptyState title="No companies found" detail="Change the filters or add a company through the approved source-discovery flow."/>:<><OperationalTable label="Companies"><thead><tr><th>Company</th><th>ATS / source</th><th>Active</th><th>Connector health</th><th>Last scan</th><th>Jobs</th><th>Failures</th><th>Primary action</th></tr></thead><tbody>{data.companies.map(c=><tr key={c.id}><td><strong>{c.name}</strong><div className="admin-meta">#{c.id} · {c.resolutionStatus}</div></td><td>{c.sourceType}</td><td><AdminStatus status={c.isActive?"healthy":"disabled"} label={c.isActive?"Active":"Paused"}/></td><td><AdminStatus status={c.connectorHealth}/></td><td>{c.lastScannedAt?new Date(c.lastScannedAt).toLocaleString():"Never"}</td><td>{c.activeJobs}</td><td>{c.consecutiveFailures}</td><td><div className="admin-row-actions"><button className="admin-button admin-button-primary" disabled={busy===c.id||!c.isActive} onClick={()=>void scan(c)}>{busy===c.id?"Working…":"Scan"}</button><details><summary aria-label={`More actions for ${c.name}`}>•••</summary><div><button type="button" onClick={()=>setConfirm({company:c,action:"toggle"})}>{c.isActive?"Pause":"Resume"}</button><button type="button" onClick={()=>setConfirm({company:c,action:"delete"})}>Delete</button></div></details></div></td></tr>)}</tbody></OperationalTable><OperationalCardList>{data.companies.map(c=><article key={c.id} className="admin-card admin-mobile-card"><div><h2>{c.name}</h2><p>{c.sourceType} · {c.activeJobs} active jobs</p></div><AdminStatus status={c.connectorHealth}/><button className="admin-button admin-button-primary" disabled={busy===c.id||!c.isActive} onClick={()=>void scan(c)}>Scan</button><TechnicalDetails><p>{c.lastErrorMessage??c.discoveryReason??"No failure detail"}</p></TechnicalDetails></article>)}</OperationalCardList></>}
    <nav className="admin-pagination" aria-label="Company pages"><button className="admin-button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {data.page} of {data.totalPages} · {data.total.toLocaleString()} companies</span><button className="admin-button" disabled={page>=data.totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></nav>
    <AdminConfirmDialog open={confirm!==null} title={confirm?.action==="delete"?`Delete ${confirm.company.name}?`:`${confirm?.company.isActive?"Pause":"Resume"} ${confirm?.company.name}?`} description={confirm?.action==="delete"?"This removes the company and its source configuration. Existing backend preconditions remain authoritative.":"This changes whether scheduled scans include this company."} confirmLabel={confirm?.action==="delete"?"Delete company":confirm?.company.isActive?"Pause company":"Resume company"} destructive={confirm?.action==="delete"} busy={busy!==null} onClose={()=>setConfirm(null)} onConfirm={()=>void confirmAction()}/>
  </div>;
}
