"use client";

import { useCallback, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AdminConfirmDialog, AdminEmptyState, AdminErrorState, AdminLoadingState, AdminPageHeader, AdminStatus, HealthTile, OperationalTable, TechnicalDetails } from "@/components/admin";
import { useAdminCandidate } from "@/lib/admin/AdminContext";

type Provider={provider:string;label:string;eligibleCompanies:number;recentSuccessfulScans:number;recentFailedScans:number;successRate:number|null;recoveringCount:number;needsReviewCount:number;downCount:number;healthyCount:number;activeJobs:number;lastSuccess:string|null;lastFailure:string|null;interventionState:string};
type Run={id:number;company:string;provider:string;startedAt:string;finishedAt:string;durationMs:number;status:string;discovered:number;added:number;updated:number;closed:number;errorCategory:string|null;errorMessage:string|null};
type Proposal={id:number;company_id:number;proposed_source_type:string;proposed_board_token:string;confidence:string;validation_status:string;status:string};
type Projection={generatedAt:string;settings:{scanEnabled:boolean};lock:{held:boolean;acquiredAt?:string|null};reliability:{healthy:number;recovering:number;needsReview:number;down:number;unknown:number};providers:Provider[];runs:Run[];proposals:Proposal[];unresolvedCompanies:Array<{id:number;name:string;careerPageUrl:string|null;resolutionStatus:string;suspectedAts:string|null}>};
type Tab="status"|"history"|"connectors";

export default function AdminScannerPage(){
  const {candidateId}=useAdminCandidate();const searchParams=useSearchParams();const initial=searchParams.get("tab");const [tab,setTab]=useState<Tab>(initial==="connectors"||initial==="history"?initial:"status");const [data,setData]=useState<Projection|null>(null);const [error,setError]=useState<string|null>(null);const [requestCompany,setRequestCompany]=useState("");const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState<Proposal|null>(null);
  const load=useCallback(async()=>{try{const res=await fetch(`/api/admin/scanner?candidateId=${candidateId}&limit=50`);if(!res.ok)throw new Error((await res.json()).error??"Scanner unavailable");setData(await res.json());setError(null)}catch(e){setError(e instanceof Error?e.message:"Scanner unavailable")}},[candidateId]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  async function requestConnector(){if(!requestCompany)return;setBusy(true);try{const res=await fetch(`/api/companies/${requestCompany}/discover?candidateId=${candidateId}`,{method:"POST"});const json=await res.json();if(!res.ok)throw new Error(json.error??"Connector request failed");await load()}catch(e){setError(e instanceof Error?e.message:"Connector request failed")}finally{setBusy(false)}}
  async function decide(proposal:Proposal,action:"approve"|"reject"){setBusy(true);try{const res=await fetch(`/api/companies/${proposal.company_id}/source-proposals/${proposal.id}/${action}?candidateId=${candidateId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(!res.ok)throw new Error((await res.json()).error??"Proposal action failed");setConfirm(null);await load()}catch(e){setError(e instanceof Error?e.message:"Proposal action failed")}finally{setBusy(false)}}
  if(error&&!data)return <AdminErrorState detail={error} retry={()=>void load()}/>;if(!data)return <AdminLoadingState label="Loading scanner operations"/>;
  return <div className="admin-page-stack"><AdminPageHeader eyebrow="Discovery" title="Scanner" description="Scanner status, bounded run history, connector reliability, coverage, and reviewed source proposals." actions={<button className="admin-button" onClick={()=>void load()}>Refresh</button>}/>{error&&<div className="admin-inline-error" role="alert">{error}</div>}
    <div className="admin-tabs" role="tablist" aria-label="Scanner sections">{(["status","history","connectors"] as Tab[]).map(item=><button key={item} role="tab" aria-selected={tab===item} onClick={()=>setTab(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>
    {tab==="status"&&<><div className="admin-health-grid admin-health-grid-four"><HealthTile label="Scanner" status={!data.settings.scanEnabled?"disabled":data.lock.held?"running":"idle"} detail={data.lock.held?"Scan lease is held":"No active scan lease"}/><HealthTile label="Healthy connectors" status="healthy" value={data.reliability.healthy}/><HealthTile label="Needs intervention" status={data.reliability.down?"needs_intervention":"healthy"} value={data.reliability.down}/><HealthTile label="Recovering" status={data.reliability.recovering?"degraded":"healthy"} value={data.reliability.recovering}/></div><section><h2 className="admin-section-title">Current state</h2><div className="admin-operational-card"><dl className="admin-metric-list"><div><dt>Enabled</dt><dd>{data.settings.scanEnabled?"Yes":"No"}</dd></div><div><dt>Current activity</dt><dd>{data.lock.held?"Running":"Idle"}</dd></div><div><dt>Last run</dt><dd>{data.runs[0]?new Date(data.runs[0].finishedAt).toLocaleString():"Never"}</dd></div><div><dt>Last outcome</dt><dd>{data.runs[0]?.status??"Unknown"}</dd></div></dl></div></section></>}
    {tab==="history"&&(data.runs.length?<OperationalTable label="Recent scan history"><thead><tr><th>Company</th><th>ATS</th><th>Started</th><th>Status</th><th>Discovered</th><th>Added</th><th>Updated</th><th>Closed</th><th>Duration</th></tr></thead><tbody>{data.runs.map(run=><tr key={run.id}><td>{run.company}</td><td>{run.provider}</td><td>{new Date(run.startedAt).toLocaleString()}</td><td><AdminStatus status={run.status==="success"?"completed":run.status==="partial"?"degraded":"failed"} label={run.status}/></td><td>{run.discovered}</td><td>{run.added}</td><td>{run.updated}</td><td>{run.closed}</td><td>{(run.durationMs/1000).toFixed(1)}s<TechnicalDetails><p>{run.errorCategory??"No error category"} · {run.errorMessage??"No error"}</p></TechnicalDetails></td></tr>)}</tbody></OperationalTable>:<AdminEmptyState title="No scan history" detail="No persisted scan runs are available."/>)}
    {tab==="connectors"&&<><section><div className="admin-section-heading"><div><h2 className="admin-section-title">Supported connectors</h2><p>The full supported catalog is shown. Reliability and coverage are derived from existing company, job, and scan records; unconfigured connectors remain explicit.</p></div></div><OperationalTable label="Supported ATS connectors"><thead><tr><th>Connector</th><th>Health</th><th>Reliability</th><th>Coverage</th><th>Companies</th><th>Last success</th><th>Last failure</th><th>Intervention</th></tr></thead><tbody>{data.providers.map(p=><tr key={p.provider}><td><strong>{p.label}</strong><div className="admin-mono-subtle">{p.provider}</div></td><td><AdminStatus status={p.downCount?"degraded":p.healthyCount?"healthy":"unknown"}/></td><td>{p.successRate===null?"No recent attempts":`${Math.round(p.successRate*100)}%`}</td><td>{p.activeJobs.toLocaleString()} active jobs</td><td>{p.eligibleCompanies}</td><td>{p.lastSuccess?new Date(p.lastSuccess).toLocaleString():"Never"}</td><td>{p.lastFailure?new Date(p.lastFailure).toLocaleString():"Never"}</td><td><AdminStatus status={p.interventionState==="Healthy"?"healthy":p.interventionState==="Recovering"?"degraded":p.interventionState==="Not configured"?"unknown":"needs_intervention"} label={p.interventionState}/></td></tr>)}</tbody></OperationalTable></section>
      <section className="admin-two-column"><div><h2 className="admin-section-title">Add or request a connector</h2><div className="admin-operational-card"><p className="admin-card-description">Choose an existing unresolved company. Career-Ops runs the bounded approved discovery flow. Unsupported or unvalidated endpoints remain unresolved or become review proposals; this never activates an arbitrary connector.</p><label className="admin-field"><span>Unresolved company</span><select value={requestCompany} onChange={e=>setRequestCompany(e.target.value)}><option value="">Select a company</option>{data.unresolvedCompanies.map(c=><option key={c.id} value={c.id}>{c.name} · {c.resolutionStatus}{c.suspectedAts?` · ${c.suspectedAts}`:""}</option>)}</select></label><button className="admin-button admin-button-primary" disabled={!requestCompany||busy} onClick={()=>void requestConnector()}>{busy?"Checking…":"Request connector review"}</button></div></div><div><h2 className="admin-section-title">Source proposals</h2>{data.proposals.length?<ul className="admin-intervention-list">{data.proposals.map(p=><li key={p.id}><div><h3>{p.proposed_source_type}</h3><p>Company #{p.company_id} · {p.confidence} · {p.validation_status}</p></div><div className="admin-row-actions"><button className="admin-button" disabled={busy||!(p.confidence==="HIGH"&&p.validation_status==="VALIDATED_JOBS")} onClick={()=>setConfirm(p)}>Approve</button><button className="admin-button" disabled={busy} onClick={()=>void decide(p,"reject")}>Reject</button></div></li>)}</ul>:<AdminEmptyState title="No pending proposals" detail="No connector source candidate is waiting for review."/>}</div></section></>}
    <AdminConfirmDialog open={confirm!==null} title="Approve validated connector source?" description="This applies only an existing HIGH-confidence, VALIDATED_JOBS source proposal. It does not mark the connector healthy or run a scan." confirmLabel="Approve source" busy={busy} onClose={()=>setConfirm(null)} onConfirm={()=>confirm&&void decide(confirm,"approve")}/>
  </div>;
}
